default:
  tags:
    - docker
    - openhpi-cloud

stages:
  - deploy

trigger-bootstrap-build:
  stage: deploy
  needs: []
  trigger:
    project: bp_defiance/bake-defiance
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
